import type { CSSProperties } from 'react'

export const adminUsersPageStyles: Record<string, CSSProperties> = {
  main: { flex: 1, overflowY: 'auto', background: '#020617', minHeight: '100vh' },
  wrapper: { padding: 24, maxWidth: 900, margin: '0 auto' },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
    flexWrap: 'wrap',
    marginBottom: 24,
  },
  title: { fontFamily: 'Syne, sans-serif', fontSize: 24, fontWeight: 800, color: 'white', marginBottom: 4 },
  subtitle: { color: '#94a3b8', fontSize: 13, marginBottom: 0 },
  btnCreate: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: '#22d3ee',
    border: 'none',
    borderRadius: 12,
    padding: '10px 20px',
    fontSize: 13,
    fontWeight: 700,
    color: '#0f172a',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  error: {
    background: 'rgba(239,68,68,.15)',
    border: '1px solid #ef4444',
    borderRadius: 12,
    padding: '12px 16px',
    color: '#fca5a5',
    fontSize: 13,
    marginBottom: 24,
  },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 24 },
  statCard: { background: '#1e293b', border: '1px solid #334155', borderRadius: 16, padding: 16 },
  statValue: { fontFamily: 'Syne, sans-serif', fontSize: 28, fontWeight: 900, color: 'white', marginBottom: 8 },
  card: { background: '#0f172a', border: '1px solid #1e293b', borderRadius: 20, padding: 0, overflow: 'hidden' },
  table: { borderCollapse: 'collapse', width: '100%' },
  th: {
    textAlign: 'left',
    padding: '10px 20px',
    fontSize: 11,
    color: '#64748b',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    borderBottom: '1px solid #1e293b',
  },
  tr: {},
  td: { padding: '12px 20px', borderBottom: '1px solid #1e293b', fontSize: 13 },
  userCell: { display: 'flex', alignItems: 'center', gap: 10, minWidth: 0 },
  userName: { color: 'white', fontWeight: 500 },
  userEmail: { color: '#64748b', fontSize: 11 },
  contact: { color: '#94a3b8', fontSize: 12 },
  unit: { color: '#94a3b8', fontSize: 12 },
  linkBtn: { background: 'none', border: 'none', color: '#22d3ee', fontWeight: 600, fontSize: 12, cursor: 'pointer' },
  empty: { padding: 40, textAlign: 'center', color: '#64748b', fontSize: 13 },
}

export const editUserModalStyles: Record<string, CSSProperties> = {
  root: {
    display: 'flex',
    overflow: 'hidden',
    borderRadius: 16,
    margin: -24,
  },
  accent: {
    width: 5,
    flexShrink: 0,
    background: 'linear-gradient(180deg, #22d3ee, #818cf8)',
  },
  body: {
    flex: 1,
    padding: '22px 20px 18px',
  },
  title: {
    fontSize: 11,
    fontWeight: 700,
    color: '#22d3ee',
    textTransform: 'uppercase',
    letterSpacing: '0.09em',
    margin: '0 0 16px',
  },
  userRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
    paddingBottom: 16,
    borderBottom: '0.5px solid #1e293b',
  },
  userName: {
    color: 'white',
    fontSize: 14,
    fontWeight: 600,
    margin: '0 0 2px',
  },
  userEmail: {
    color: '#96a1b0',
    fontSize: 11,
    margin: '0 0 1px',
  },
  userMeta: {
    color: '#96a1b0',
    fontSize: 11,
    margin: 0,
  },
  sectionLabel: {
    fontSize: 10,
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: '0.07em',
    margin: '0 0 9px',
  },
  editHint: {
    fontSize: 11,
    color: '#94a3b8',
    margin: '0 0 10px',
    lineHeight: 1.45,
  },
  pillGroup: {
    display: 'flex',
    gap: 7,
    flexWrap: 'wrap',
    marginBottom: 18,
  },
  pill: {
    padding: '7px 15px',
    borderRadius: 99,
    border: '1px solid #1e293b',
    fontSize: 12,
    color: '#64748b',
    background: 'transparent',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 8,
    paddingTop: 16,
    borderTop: '0.5px solid #1e293b',
  },
  btnCancel: {
    background: 'transparent',
    border: '1px solid #1e293b',
    borderRadius: 10,
    padding: '9px 18px',
    fontSize: 13,
    color: '#64748b',
    cursor: 'pointer',
  },
  btnSave: {
    background: '#22d3ee',
    border: 'none',
    borderRadius: 10,
    padding: '9px 22px',
    fontSize: 13,
    fontWeight: 700,
    color: '#0f172a',
    cursor: 'pointer',
    transition: 'background .2s',
  },
  field: { display: 'flex', flexDirection: 'column', gap: 5 },
  select: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 10,
    padding: '9px 12px',
    fontSize: 13,
    color: 'white',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  fieldHint: {
    fontSize: 10,
    color: '#64748b',
    margin: '4px 0 0',
    lineHeight: 1.4,
  },
  inlineError: {
    background: 'rgba(248,113,113,.12)',
    border: '1px solid rgba(248,113,113,.4)',
    borderRadius: 10,
    padding: '10px 12px',
    color: '#fca5a5',
    fontSize: 12,
    marginBottom: 14,
  },
}

export const createUserModalStyles: Record<string, CSSProperties> = {
  root: { display: 'flex', overflow: 'hidden', borderRadius: 16, margin: -24 },
  accent: { width: 5, flexShrink: 0, background: 'linear-gradient(180deg,#22d3ee,#818cf8)' },
  body: { flex: 1, padding: '22px 20px 18px' },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 11,
    fontWeight: 700,
    color: '#22d3ee',
    textTransform: 'uppercase',
    letterSpacing: '.09em',
    margin: 0,
  },
  inlineError: {
    background: 'rgba(248,113,113,.12)',
    border: '1px solid rgba(248,113,113,.4)',
    borderRadius: 10,
    padding: '10px 12px',
    color: '#fca5a5',
    fontSize: 12,
    marginBottom: 14,
  },
  steps: { display: 'flex', alignItems: 'center', gap: 6, marginBottom: 20 },
  dot: {
    width: 26,
    height: 26,
    borderRadius: '50%',
    border: '1px solid #334155',
    fontSize: 11,
    fontWeight: 700,
    color: '#64748b',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    flexShrink: 0,
  },
  stepLine: { flex: 1, height: 1, background: '#1e293b', transition: 'background .3s' },
  row2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 12 },
  field: { display: 'flex', flexDirection: 'column', gap: 5 },
  fieldLabel: { fontSize: 10, color: '#475569', textTransform: 'uppercase', letterSpacing: '.07em' },
  input: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 10,
    padding: '9px 12px',
    fontSize: 13,
    color: 'white',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  select: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 10,
    padding: '9px 12px',
    fontSize: 13,
    color: 'white',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  fieldHint: {
    fontSize: 10,
    color: '#64748b',
    margin: '4px 0 0',
    lineHeight: 1.4,
  },
  sectionLabel: {
    fontSize: 10,
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: '.07em',
    margin: '0 0 9px',
  },
  pillGroup: { display: 'flex', gap: 7, flexWrap: 'wrap', marginBottom: 18 },
  pill: {
    padding: '7px 15px',
    borderRadius: 99,
    border: '1px solid #1e293b',
    fontSize: 12,
    color: '#64748b',
    background: 'transparent',
    cursor: 'pointer',
  },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 4,
  },
  toggleLabel: { fontSize: 12, color: '#94a3b8', marginBottom: 2 },
  toggleSub: { fontSize: 10, color: '#475569', lineHeight: 1.45 },
  toggle: {
    width: 36,
    height: 20,
    borderRadius: 99,
    background: '#1e293b',
    border: '1px solid #334155',
    position: 'relative',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'background .15s',
    padding: 0,
  },
  toggleKnob: {
    width: 14,
    height: 14,
    borderRadius: '50%',
    background: '#64748b',
    position: 'absolute',
    top: 2,
    left: 2,
    transition: 'all .2s',
    pointerEvents: 'none',
  },
  previewChip: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 12,
    padding: '12px 14px',
    marginBottom: 14,
  },
  previewAvatar: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    background: 'rgba(34,211,238,.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 700,
    color: '#22d3ee',
    flexShrink: 0,
  },
  previewName: { color: 'white', fontSize: 14, fontWeight: 600, marginBottom: 2 },
  previewMeta: { color: '#64748b', fontSize: 11 },
  summary: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 12,
    padding: 14,
    fontSize: 12,
    lineHeight: 2,
  },
  summaryRow: { display: 'flex', justifyContent: 'space-between' },
  summaryKey: { color: '#475569' },
  summaryVal: { color: 'white' },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    paddingTop: 14,
    borderTop: '.5px solid #1e293b',
  },
  stepHint: { fontSize: 11, color: '#475569' },
  btnCancel: {
    background: 'transparent',
    border: '1px solid #1e293b',
    borderRadius: 10,
    padding: '9px 16px',
    fontSize: 13,
    color: '#64748b',
    cursor: 'pointer',
  },
  btnSave: {
    background: '#22d3ee',
    border: 'none',
    borderRadius: 10,
    padding: '9px 22px',
    fontSize: 13,
    fontWeight: 700,
    color: '#0f172a',
    cursor: 'pointer',
    transition: 'background .2s',
  },
}
